### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by pepijndevos**
Document new locations of toolchain, docs and the current lack of a deploy target.

### CODE REVIEW

**Comment by pepijndevos** [comment]
With my Ubuntu toolchain I had to configure with `./configure --host=arm-none-eabi BOARD=ev3 LDFLAGS="--specs=nosys.specs"`, I'm not sure if this is just a particularity of my system, or something that should be in the documentation.

**Comment by pepijndevos** [comment]
Another missing piece of info: Yet another revision of the readme mentions `qemu/readme.txt` for info about running the OS on qemu. No such file exist in any revision I've looked at so far.

**Comment by oaken-source** [comment]
yes, there is a TODO section in the readme for this.

**Comment by oaken-source** [comment]
by the way, please feel free to add your name to the THANKS and AUTHORS files on your next contribution.

**Pull request merged**
